### PR TITLE
Added possibility to intercept stomp frames

### PR DESCRIPTION
**Pull request by mastanik**
Initially I was trying to log all the incoming stomp frames from the client on a server side, but could not find any easy way of doing this. This pr adds possibility to intercept stomp frames via interceptor section in activemq-configuration.xml. 

Interceptor list was already passed as a parameter to StompProtocolManager constructor, but was not used in any way. I decided to introduce new abstract class which implements Interceptor interface as the simplest solution and then invoke its intercept method like it is done with the regular interceptors. 

Clients need to extend this class and put it under activemq class path, just as a regular jms interceptor.

Looking forward to your comments, and feel free to reject it in case it does not make any sense.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Nicely done... +1 on me for a merge

**Comment by mastanik** [comment]
Yes, sure, I will update this pr when it is done

**Comment by clebertsuconic** [comment]
I will hold the PR open until you do it then

**Comment by clebertsuconic** [comment]
If you have a chance also, add a paragraph to the docs :) I will do it right away if you don't have time to do it.. but please advise if that's the case so I will do the docs.

**Comment by mastanik** [comment]
Sure, I will update it as well

**Comment by mastanik** [comment]
Added 2 new commits with outgoing frames support and new stomp interceptor paragrap

**Comment by clebertsuconic** [comment]
I will merge it later today when I get home

**Comment by clebertsuconic** [comment]
There's a risk of something wrong with your PR. We have a release tomorrow so I will wait until the release is done before I merge this, ok?


I'm concerned with the case with having a regular interceptor. and a stomp acceptor where no acceptors were supposed to be used and having a class cast exception.


I will do some work on this right after the release

**Comment by mastanik** [comment]
Yes, it's ok.
If there would be any problems with my PR please let me know.

**Comment by clebertsuconic** [comment]
as I promised I would work on this after the release...#191 

The release is now under vote, so I continued your work at #191 where I did some refactoring.


As soon as #191 is merged this one should be closed automatically.


If you could please review my changes

**Comment by clebertsuconic** [comment]
Can you close this one please ?  I have imported your commit into mine

**Pull request closed without merging**
