### PR TITLE
Management Methods for first message timestamp

### PR DESCRIPTION
**Pull request by dpocock**

### CODE REVIEW

**Comment by dpocock** [comment]
This was also submitted to HornetQ:
https://github.com/hornetq/hornetq/pull/1988

**Comment by dpocock** [comment]
https://issues.apache.org/jira/browse/ACTIVEMQ6-79

**Comment by mtaylor** [comment]
ok to test

**Comment by jbertram** [comment]
Please add a few tests to ensure the new methods are working properly.

**Comment by dpocock** [comment]
Can you please let me know if the unit tests are sufficient?

What is the recommended way to run the integration tests to test a single change?  The full set appears to run for a long time.

**Comment by jbertram** [comment]
The test looks fine, but you need to squash the two commits together into one commit.

See https://github.com/apache/activemq-6#tests for instructions on running individual tests from the command line.

Also you should added corresponding methods to org.apache.activemq.api.jms.management.JMSQueueControl so that your new management methods can be used for JMS queues as well.

**Comment by dpocock** [comment]
JMS stuff added and commits squashed

**Comment by Humbedooh** [comment]
testing whether this hits the ML, ignore :)

**Comment by clebertsuconic** [comment]
@dpocock  sorry it took us this long to merge this...

**Pull request closed without merging**
