### PR TITLE
ACTIVEMQ6-55: prevent NPE when closing a link with no context

### PR DESCRIPTION
**Pull request by gemmellr**

### CODE REVIEW

**Comment by mtaylor** [comment]
@gemmellr Hi Robbie, could you also add test for this?

**Comment by gemmellr** [comment]
@mtaylor I added a test for the listener method throwing the NPE. I had to tweak the code slightly to access the listener, which seemed vastly preferable to the various alternatives I tried first to be able to test the method.

**Comment by mtaylor** [comment]
@gemmellr That's great Robby thanks a lot.

**Comment by dkulp** [comment]
Just a test comment as infra wants a comment on a pull request to test the integration with the mailing list.  Sorry for the noise.

**Comment by dkulp** [comment]
Another test as INFRA keeps trying to get this working....  Sorry for the noise.

**Pull request closed without merging**
