### PR TITLE
Apache Rat- Exclude target dirs and intellij files

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by jbertram** [comment]
@gaohoward, can you take a look at this and make sure these new exclusions don't miss anything?  My local build was stalling and these new excludes fixed that problem, but I want to make sure we're still covered appropriately.

**Comment by clebertsuconic** [comment]
Can you use this time that you are touching the pom and remove the twitter lines... it doesn't exist any longer

**Comment by mtaylor** [comment]
@clebertsuconic sorry I'm not quite sure what you mean here.

**Comment by clebertsuconic** [comment]
Added as an inline comment ^

**Comment by mtaylor** [comment]
@clebertsuconic thanks I've updated accordingly

**Comment by andytaylor** [comment]
i'll merge

**Pull request merged**
