### PR TITLE
improved logging on Netty Acceptor

### PR DESCRIPTION
**Pull request by andytaylor**

### CODE REVIEW

**Comment by andytaylor** [comment]
this has failed but i dont think its my changes as i ran the full test suite, could someone check.

**Comment by mtaylor** [comment]
Ok to test

**Comment by mtaylor** [comment]
@andytaylor I've opened a new PR here: #123 with your commit.  Should let me rebase and re run tests.  Closes this PR.

**Comment by mtaylor** [comment]
@andytaylor Actually you'll need to close I don't have permissions.

**Comment by mtaylor** [comment]
@andytaylor FYI PR check passed on #123.  I've merged.  Please close this PR when you get a chance.  Thanks,

**Pull request closed without merging**
