### PR TITLE
ACTIVEMQ6-89  Interceptors on Stomp and some other small changes

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
DO NOT MERGE THIS YET... there are test failures on the integration tests

**Comment by mastanik** [comment]
looks good

**Comment by mtaylor** [comment]
@clebertsuconic This was probably mentioned earlier, but this seems like a considerable change.  Can we hold off merging until after the release.  Thanks.

**Comment by clebertsuconic** [comment]
Only after the release please

**Comment by mtaylor** [comment]
Looks good @clebertsuconic . Ack.

**Pull request merged**
