### PR TITLE
ACTIVEMQ6-7 - Improve Serialization on Connection Factory

### PR DESCRIPTION
**Pull request by andytaylor**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Why Broadcast configuration still serializable? Shouldn't we remove serialization from mostly everything? only keeping the ConnectionFactories as serializable?

that would help us prevent any further errors.


What about sub-classes of ActiveMQConnectionFactory.. are they all working with the externalization?

**Comment by clebertsuconic** [comment]
DiscoveryGroupConfiguration also serializable... I thought we agreed on removing that?

**Comment by clebertsuconic** [comment]
URISchema:: allowableProperties on setData.

Can't we use BeanUtils here and just do a simple loop?

      if (allowableProperties.contains("host"))
      {
         properties.put("host", uri.getHost());
      }
      if (allowableProperties.contains("port"))
      {
         properties.put("port", uri.getPort());
      }
      if (allowableProperties.contains("userInfo"))
      {
         properties.put("userInfo", uri.getUserInfo());
      }

**Comment by clebertsuconic** [comment]
ActiveMQJMSConnectionFactory:

I think you still need the serialVersionUID otherwise the JDK will assign you one.

When you use writeExternal, the Object serializatoin will still "print" the serialVersionUID somewhere on the wire and if that changed based on any decision from the JDK, you may end up with incompatible code.

**Comment by clebertsuconic** [comment]
Very nice work! These are all minor points...

I think there's a System.out that I forgot.. so if you could remove it please?


It's probably better to keep your and mine commit separates just for historical reasons.

**Comment by andytaylor** [comment]
@clebertsuconic re serializable, it turns out we currently need configs to be serialazable because of the configuration.copy() method which does a deep copy. We could find a better way to do this but we should do it via a different JIRA.

**Comment by andytaylor** [comment]
good catch, ive added the serialVersionUID back on ActiveMQJMSConnectionFactory

**Comment by andytaylor** [comment]
re comment 'URISchema:: allowableProperties on setData.' no we cant as we are copying toa map, alos we need to explicitly pull these out of the uri. also this was your code @clebertsuconic :)

**Comment by andytaylor** [comment]
ive rebased and this is good to go

**Pull request merged**
