### PR TITLE
added some exclusions to the RAT plugin

### PR DESCRIPTION
**Pull request by andytaylor**
added some exclusions to the RAT plugin for when users build and redirect the output to log files

### CODE REVIEW

**Comment by artnaseef** [comment]
I think this helps, but want to see more.  The copyright check here is very aggressive and assumes that anyone working with the sources will only ever be working with files that contain a matching license.

We can do better here, I'm sure of it.  Here are some ideas:
a. Only run the copyright check on release build, or
b. Only run the copyright check when the build user specifies a maven profile specific to that check, or
c. Limit the copyright check to files that are distributed with the original sources (i.e. only files from git)

It is important to make development for all users easy.  Apache projects release source code, not binaries (although binaries are allowed as a convenience).  This means we anticipate many users working with the source code.  This even raises the question of whether it's valid in the Apache ecosystem to restrict files in the development tree to those with the Apache license; the license itself states "You may add Your own copyright statement to Your modifications".  This check appears to conflict with that statement.

Let's find an approach that makes Apache releases meet the required licensing without passing that restriction outside of Apache.  For comparison, the existing ActiveMQ release process uses a manual step to execute the copyright check.

**Comment by andytaylor** [comment]
I actually took tose excludes from the ActiveMQ pom however i thought (wrongly) that it was always run. I will update this pr and add a new profile have a manual step during the release process and ci builds the same as ActiveMQ. please no one merge this PR.

**Comment by artnaseef** [comment]
Thanks Andy.

**Comment by andytaylor** [comment]
improved via https://github.com/apache/activemq-6/pull/194

**Pull request merged**
