### PR TITLE
ACTIVEMQ6-94 Large Message over Bridge and server's transfer

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@gaohoward  can you take a look on my changes please?

This will close your PR.. maybe you should close #197 already...


I would appreciate having at least 2 people looking into this PR (Martyn/Andy / @jbertram ?)

**Comment by gaohoward** [comment]
give me some time to test it. I remember this producer window probably won't fix it.

**Comment by gaohoward** [comment]
Ok although the unit test pass, but with manual test I sometimes got OOM still. Look at this code in ChannelImpl.send():

resendCache.add(packet);

https://github.com/clebertsuconic/activemq-6/blob/new-Bridge/activemq-core-client/src/main/java/org/apache/activemq/core/protocol/core/impl/ChannelImpl.java#L294

When sending a large, each packet holds a chunk of it, and because it's stored in the resendCache, it doesn't get gc'ed after the bytes are sent to the other node. Eventually before the large send complete, all previous sent chunks will be held in memory. 

any comment?

Howard

**Comment by clebertsuconic** [comment]
I will take a look...

But the only thing supposed to wait on the channel is flow control.... that previous fix is not valid (it would cause serious performance issues on regular cases).

Besides 50M minLargeMessageSize is an invalid test.

**Comment by gaohoward** [comment]
Ah, in the test setting 50M is just to make the test run faster. consider it's 3G large message...

**Comment by clebertsuconic** [comment]
@gaohoward if you are sending large messages this huge you will have to set the new setting on producerWindowSize through the bridge. that's the only thing we should support.

With a 50M min largeMessagesize you will be allocating huge buffers over the Native Layer as well.. it's bound to fail.


I have run your test with 3G files and it's working fine. So, this should be sufficient to fix this issue on master. I really don't want any layer to wait on resendCache to exaust.. that will cause huge delays on average sized large messages (such as 10M, 1M..  since you would require a round trip network for every chunk sent).


I think we are fine with this fix here

**Pull request merged**
