### PR TITLE
ACTIVEMQ6-97 - Change HQ to AMQ for properties/headers/doc. Remove as mu...

### PR DESCRIPTION
**Pull request by jgenender**
...ch HQ as possible and change to AMQ to make this close to the ActiveMQ project.

### CODE REVIEW

**Comment by jbertram** [comment]
My understanding is that these properties weren't change due to compatibility with older HornetQ clients.  Have you tested these changes with HornetQ clients to ensure there are no regressions?

**Comment by clebertsuconic** [comment]
We will merge this.. I just want to have a thought about client compatibility and look through this.

**Comment by clebertsuconic** [comment]
We will need to fix the testsuite before being able to merge this one...

@jgenender  you used your master for this... this PR will probably be open for a few days...

Can you make sure you open a new branch if you send another PR non related to this?

I will need a few days before I can merge this mainly because of the testsuite.

**Comment by jgenender** [comment]
Absolutely.

Thanks,

Jeff

**Pull request closed without merging**
